services:
  database:
    image: 'mariadb:11'
    environment:
      - MARIADB_DATABASE=raspadmin
      - MARIADB_ROOT_PASSWORD=secret
    volumes:
      - './mysql:/var/lib/mysql'

  app:
    image: 'mundotv789123/raspadmin'
    environment:
      - 'FILES_PATH=/home/app/files'
      - 'MEDIA_THUMB=true'

      - 'AUTH_ENABLED=false'
      - 'USERNAME=admin'
      - 'PASSWORD=admin'

      - 'DB_TYPE=mysql'
      - 'MYSQL_HOST=database'
      - 'MYSQL_DB=raspadmin'
      - 'MYSQL_USER=root'
      - 'MYSQL_PASSWORD=secret'
    volumes:
      - './data:/home/app/data'
      - './files:/home/app/files'
    ports:
      - '8080:8080'
