version: '3.1'
services:
  raspadmin:
    image: 'mundotv789123/raspadmin'
    container_name: 'raspadmin_files'
    ports:
    - '8080:3000'
    volumes:
    - './files:/app/files'
    environment:
      NEXT_PUBLIC_APP_NAME: 'RaspAdmin'
      API_AUTH_KEY: ''
      API_USERNAME: 'admin'
      API_PASSWORD: 'admin'
