name: Docker Image Deploy

on:
  workflow_call:
    secrets:
      SERVER_IP:
        required: false
      SERVER_KEY:
        required: false

  workflow_dispatch:

jobs:
  deploy-dev:
    runs-on: self-hosted
    steps:
      - name: executing remote ssh commands
        uses: appleboy/ssh-action@v1
        with:
          username: root
          host: ${{ secrets.SERVER_IP }}
          key: ${{ secrets.SERVER_KEY }}
          port: 22
          script: |
            cd /srv/raspadmin
            docker compose pull app && docker compose down app
            docker compose up -d app
            docker image prune -f
