name: Docker Image Deploy

on:
  workflow_call:
  workflow_dispatch:
    inputs:
      tag:
        default: 'develop'
        required: false
        type: string

jobs:
  deploy-dev:
    runs-on: self-hosted
    if: github.ref == 'refs/heads/develop'
    steps:
      - name: executing remote ssh commands
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.SERVER_IP }}
          username: root
          key: ${{ secrets.SERVER_KEY }}
          port: 22
          script: |
            cd /srv/raspadmin
            docker compose pull app && docker compose down app
            docker compose up -d
            docker image prune -f
